# I am not rude enough to remove Aylur from funding, because it is ultimately his
# work that deserves a massive portion of the credit. However I also think I deserve
# to be compensated for whatever time I spend maintaining this project, SHOULD it
# be helpful to someone, sometime.
github: [NotAShelf]
ko_fi: [aylur]
