import js from '@eslint/js';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';

export default [
    {
        ignores: [
            'example/**',
            'types/**',
            'gi-types/**',
            '_build/**',
            'build/**',
            'result/**',
            'node_modules/**',
            'pnpm-lock.yaml',
            'package-lock.json',
            'eslint.config.js',
        ],
    },
    js.configs.recommended,
    {
        files: ['**/*.{ts,js}'],
        languageOptions: {
            parser: tsParser,
            parserOptions: {
                ecmaVersion: 2022,
                sourceType: 'module',
                project: true,
                warnOnUnsupportedTypeScriptVersion: false,
            },
            globals: {
                pkg: 'readonly',
                ARGV: 'readonly',
                Debugger: 'readonly',
                GIRepositoryGType: 'readonly',
                globalThis: 'readonly',
                imports: 'readonly',
                Intl: 'readonly',
                log: 'readonly',
                logError: 'readonly',
                print: 'readonly',
                printerr: 'readonly',
                window: 'readonly',
                TextEncoder: 'readonly',
                TextDecoder: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
            },
        },
        plugins: {
            '@typescript-eslint': tsPlugin,
        },
        rules: {
            ...tsPlugin.configs.recommended.rules,
            '@typescript-eslint/ban-ts-comment': 'off',
            '@typescript-eslint/no-non-null-assertion': 'off',
            '@typescript-eslint/no-explicit-any': 'off',
            '@typescript-eslint/no-unused-vars': 'off',
            '@typescript-eslint/no-empty-interface': 'off',
            '@typescript-eslint/no-unsafe-declaration-merging': 'off',
            '@typescript-eslint/no-empty-object-type': 'off',
            'no-redeclare': 'off',
            'no-import-assign': 'off',
            'arrow-parens': ['error', 'as-needed'],
            'comma-dangle': ['error', 'always-multiline'],
            'comma-spacing': ['error', { before: false, after: true }],
            'comma-style': ['error', 'last'],
            curly: ['error', 'multi-or-nest', 'consistent'],
            'dot-location': ['error', 'property'],
            'eol-last': 'error',
            indent: ['error', 4, { SwitchCase: 1 }],
            'keyword-spacing': ['error', { before: true }],
            'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: true }],
            'padded-blocks': ['error', 'never', { allowSingleLineBlocks: false }],
            'prefer-const': 'error',
            quotes: ['error', 'single', { avoidEscape: true }],
            semi: ['error', 'always'],
            'nonblock-statement-body-position': ['error', 'below'],
            'no-trailing-spaces': 'error',
            'no-useless-escape': 'off',
            '@typescript-eslint/no-unused-expressions': 'off',
            'max-len': ['error', { code: 100 }],
            'func-call-spacing': 'error',
            'array-bracket-spacing': 'error',
            'space-before-function-paren': [
                'error',
                {
                    anonymous: 'never',
                    named: 'never',
                    asyncArrow: 'ignore',
                },
            ],
            'space-before-blocks': 'error',
            'key-spacing': 'error',
            'object-curly-spacing': ['error', 'always'],
        },
    },
];
