name: Binary Cache

on: [push, pull_request, workflow_dispatch]
jobs:
  nix:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v31

      - name: Build ags w/ types
        run: nix build --print-build-logs .#ags

      - name: Build ags without types
        run: nix build --print-build-logs .#agsNoTypes
